Public Class PatientHealthCheckData
    Public VisitationID As Long
    Public PatientID As Long
    Public AssessmentID As Long
    Public Purpose As String
    Public Details As String
    Public NotSelf As Boolean
    Public HasSeen As Boolean
    Public HasScreen As Boolean
    Public DateOfVisit As Date
    Public ReferenceNo As String
    Public FirstName As String
    Public MiddleName As String
    Public LastName As String
    Public Suffix As String
    Public BirthDate As Date
    Public Sex As String
    Public CivilStatus As String
    Public Address As String
    Public Region As String
    Public Province As String
    Public City As String
    Public Barangay As String
    Public MobileNumber As String
    Public Email As String
    Public Occupation As String
    Public Company As String
    Public ProfileDate As Date
    Public FeverChills As Boolean
    Public Cough As Boolean
    Public SoreThroat As Boolean
    Public Diarrhea As Boolean
    Public ShortnessOfBreathing As Boolean
    Public Ageusia As Boolean
    Public Anosmia As Boolean
    Public Colds As Boolean
    Public CloseContactConfirmed As Boolean
    Public CloseContactPersonExhibiting As Boolean
    Public DateOfAssesment As Date
    Public isValid As Boolean
End Class
